# Generated by Django 4.1.7 on 2023-02-17 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spr_kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Вид договора')),
            ],
            options={
                'db_table': 'spr_kind',
            },
        ),
        migrations.CreateModel(
            name='Spr_sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Признак договора')),
            ],
            options={
                'db_table': 'spr_sign',
            },
        ),
        migrations.CreateModel(
            name='Spr_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=200, verbose_name='Пользователь')),
            ],
            options={
                'db_table': 'spr_user',
            },
        ),
        migrations.CreateModel(
            name='Contract_pr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_contract', models.CharField(max_length=30, verbose_name='Номер')),
                ('d_contract', models.DateField(verbose_name='Дата')),
                ('name_work', models.CharField(max_length=300, verbose_name='Предмет договора')),
                ('summa', models.FloatField(default=0, verbose_name='Сумма')),
                ('create_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('d_cr', models.DateField(verbose_name='Дата отправки на согласование')),
                ('spr_kind', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spr_kind', to='app_eca.spr_kind', verbose_name='Вид договора')),
                ('spr_sign', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spr_sign', to='app_eca.spr_sign', verbose_name='Признак договора')),
                ('spr_user_cr', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spr_user', to='app_eca.spr_user', verbose_name='Куратор')),
            ],
            options={
                'db_table': 'contract_pr',
            },
        ),
    ]
