# Generated by Django 4.1.7 on 2023-03-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eca', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract_pr',
            options={'verbose_name': 'проект договора', 'verbose_name_plural': 'проекты'},
        ),
        migrations.AlterField(
            model_name='contract_pr',
            name='d_cr',
            field=models.DateField(null=True, verbose_name='Дата отправки на согласование'),
        ),
    ]
