# Generated by Django 4.1.7 on 2023-03-01 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_eca', '0002_alter_contract_pr_options_alter_contract_pr_d_cr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spr_smeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('shifr', models.CharField(max_length=10, verbose_name='Шифр')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'смета',
                'verbose_name_plural': 'сметы',
                'db_table': 'spr_smeta',
            },
        ),
        migrations.AlterModelOptions(
            name='spr_kind',
            options={'verbose_name': 'вид договора', 'verbose_name_plural': 'виды договоров'},
        ),
        migrations.AlterModelOptions(
            name='spr_sign',
            options={'verbose_name': 'признак договора', 'verbose_name_plural': 'признаки договоров'},
        ),
        migrations.AlterModelOptions(
            name='spr_user',
            options={'verbose_name': 'куратор', 'verbose_name_plural': 'кураторы'},
        ),
        migrations.CreateModel(
            name='Spr_smeta_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=10, verbose_name='Пункт')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('spr_smeta', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spr_smeta', to='app_eca.spr_smeta', verbose_name='Смета')),
            ],
            options={
                'verbose_name': 'пункт сметы',
                'verbose_name_plural': 'пункты сметы',
                'db_table': 'spr_smeta_item',
            },
        ),
        migrations.AddField(
            model_name='contract_pr',
            name='spr_smeta_item',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spr_smeta_item', to='app_eca.spr_smeta_item', verbose_name='Пункты сметы'),
        ),
    ]
