# Generated by Django 4.1.7 on 2023-03-07 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_eca', '0003_spr_smeta_alter_spr_kind_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spr_smeta',
            options={'ordering': ('year', 'shifr'), 'verbose_name': 'смета', 'verbose_name_plural': 'сметы'},
        ),
        migrations.AlterModelOptions(
            name='spr_smeta_item',
            options={'ordering': ('spr_smeta', 'item'), 'verbose_name': 'пункт сметы', 'verbose_name_plural': 'пункты сметы'},
        ),
        migrations.AlterField(
            model_name='contract_pr',
            name='spr_user_cr',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spr_user', to='app_eca.spr_user', verbose_name='Куратор оформления'),
        ),
    ]
