# Generated by Django 4.1.7 on 2023-03-07 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_eca', '0004_alter_spr_smeta_options_alter_spr_smeta_item_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract_pr',
            name='d_dop',
            field=models.DateField(null=True, verbose_name='Дата согласования'),
        ),
        migrations.AddField(
            model_name='contract_pr',
            name='d_gbuh',
            field=models.DateField(null=True, verbose_name='Дата согласования'),
        ),
        migrations.AddField(
            model_name='contract_pr',
            name='d_kazna',
            field=models.DateField(null=True, verbose_name='Дата согласования'),
        ),
        migrations.AddField(
            model_name='contract_pr',
            name='d_nach',
            field=models.DateField(null=True, verbose_name='Дата согласования'),
        ),
        migrations.AddField(
            model_name='contract_pr',
            name='d_oeb',
            field=models.DateField(null=True, verbose_name='Дата согласования'),
        ),
        migrations.AddField(
            model_name='contract_pr',
            name='d_oimo',
            field=models.DateField(null=True, verbose_name='Дата согласования'),
        ),
        migrations.AddField(
            model_name='contract_pr',
            name='d_ow',
            field=models.DateField(null=True, verbose_name='Дата отправки на согласование'),
        ),
        migrations.AddField(
            model_name='contract_pr',
            name='d_peo',
            field=models.DateField(null=True, verbose_name='Дата согласования'),
        ),
        migrations.AddField(
            model_name='contract_pr',
            name='d_smeta',
            field=models.DateField(null=True, verbose_name='Дата согласования'),
        ),
        migrations.AddField(
            model_name='contract_pr',
            name='d_uks',
            field=models.DateField(null=True, verbose_name='Дата согласования'),
        ),
        migrations.AddField(
            model_name='contract_pr',
            name='d_uo',
            field=models.DateField(null=True, verbose_name='Дата согласования'),
        ),
        migrations.AddField(
            model_name='contract_pr',
            name='d_uz',
            field=models.DateField(null=True, verbose_name='Дата согласования'),
        ),
        migrations.AddField(
            model_name='contract_pr',
            name='d_zdef',
            field=models.DateField(null=True, verbose_name='Дата согласования'),
        ),
        migrations.AddField(
            model_name='contract_pr',
            name='spr_smeta',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spr_smeta_main', to='app_eca.spr_smeta', verbose_name='Смета'),
        ),
        migrations.AddField(
            model_name='contract_pr',
            name='spr_user_dop',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spr_user_dop', to='app_eca.spr_user', verbose_name='Дополнительный согласователь'),
        ),
        migrations.AddField(
            model_name='contract_pr',
            name='spr_user_gbuh',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spr_user_gbuh', to='app_eca.spr_user', verbose_name='Главный бухгалтер'),
        ),
        migrations.AddField(
            model_name='contract_pr',
            name='spr_user_kazna',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spr_user_kazna', to='app_eca.spr_user', verbose_name='Начальник Казначейства'),
        ),
        migrations.AddField(
            model_name='contract_pr',
            name='spr_user_nach',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spr_user_nach', to='app_eca.spr_user', verbose_name='Начальник подразделения'),
        ),
        migrations.AddField(
            model_name='contract_pr',
            name='spr_user_oeb',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spr_user_oeb', to='app_eca.spr_user', verbose_name='Начальник ОЭБ'),
        ),
        migrations.AddField(
            model_name='contract_pr',
            name='spr_user_oimo',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spr_user_oimo', to='app_eca.spr_user', verbose_name='Начальник ОИМО'),
        ),
        migrations.AddField(
            model_name='contract_pr',
            name='spr_user_ow',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spr_user_ow', to='app_eca.spr_user', verbose_name='Куратор'),
        ),
        migrations.AddField(
            model_name='contract_pr',
            name='spr_user_peo',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spr_user_peo', to='app_eca.spr_user', verbose_name='Начальник ПЭО'),
        ),
        migrations.AddField(
            model_name='contract_pr',
            name='spr_user_smeta',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spr_user_smeta', to='app_eca.spr_user', verbose_name='Отвественный за смету'),
        ),
        migrations.AddField(
            model_name='contract_pr',
            name='spr_user_uks',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spr_user_uks', to='app_eca.spr_user', verbose_name='УКС. ЗН по учету поставок оборудования'),
        ),
        migrations.AddField(
            model_name='contract_pr',
            name='spr_user_uo',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spr_user_uo', to='app_eca.spr_user', verbose_name='Начальник ЮО'),
        ),
        migrations.AddField(
            model_name='contract_pr',
            name='spr_user_uz',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spr_user_uz', to='app_eca.spr_user', verbose_name='Начальник УЗ'),
        ),
        migrations.AddField(
            model_name='contract_pr',
            name='spr_user_zdef',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spr_user_zdef', to='app_eca.spr_user', verbose_name='ЗДЭФ'),
        ),
    ]
