# Generated by Django 4.1.7 on 2023-03-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eca', '0005_contract_pr_d_dop_contract_pr_d_gbuh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract_pr',
            name='d_registration',
            field=models.DateField(null=True, verbose_name='Дата регистрации'),
        ),
    ]
